### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by michaelli28** [nabil-k/SchoologyQuizPlus#2]
I have no clue how to use this.

**Comment by nabil-k** [comment]
This code no longer works since schoology made some updates. I will also no longer be updating the code anymore. But if you still want to load it and maybe fix it... ;) 

Check this out: https://developer.chrome.com/extensions/getstarted#manifest
Btw in the article when it says "unpacked" it's talking about the folder with all the code (which is this repo). So just download this repo and follow those instructions.
